#.travis.yml

language: node_js
node_js:
  - "8.11"

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcups2-dev

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run build

#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN
